#Needs a port mapping in AddKubernetesToDocker.ps1 when creating the cluster
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: LoadBalancer
  ports:
  - name: mysql
    port: 3307
    targetPort: 3307
  selector:
    app: mysql
