apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: k3s
servers: 1
volumes:
  - volume: C:/data/k8s:/tmp/shared
    nodeFilters:
      - server:0
      - agent:*
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
  - port: 3333:3307
    nodeFilters:
      - loadbalancer
  - port: 4222:4222
    nodeFilters:
      - loadbalancer
  - port: 8222:8222
    nodeFilters:
      - loadbalancer
  - port: 6379:6379
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: registry
    host: "0.0.0.0"
    hostPort: "5000"
    volumes:
      - C:/data/registry:/var/lib/registry # persist registry data locally
options:
  k3d:
    wait: true
    timeout: "60s"
  #k3s:
  #  extraArgs:
  #    - arg: --tls-san=192.168.0.254
  #      nodeFilters:
  #        - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
