apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: ubk3s
servers: 1
kubeAPI: 
#  host: "ubk3s"
  hostIP: "127.0.0.1"
  hostPort: "6443"
subnet: "172.28.0.0/16"
volumes:
  - volume: /data/k8s:/tmp/shared
    nodeFilters:
      - server:0
      - agent:*
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 3333:3307
    nodeFilters:
      - loadbalancer
  - port: 3333:3307
    nodeFilters:
      - loadbalancer
  - port: 4222:4222
    nodeFilters:
      - loadbalancer
  - port: 8222:8222
    nodeFilters:
      - loadbalancer
  - port: 6379:6379
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: registry.ubk3s
    host: "0.0.0.0"
    hostPort: "5000"
    volumes:
      - /data/registry:/var/lib/registry # persist registry data locally
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --tls-san=192.168.0.254
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
