apiVersion: v1
kind: Namespace
metadata:
  name: mynginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: mynginx
  labels:
    app: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: registry:5000/mynginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
  namespace: mynginx
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: mynginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mynginx
  namespace: mynginx
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "mynginx"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mynginx
            port:
              number: 80
  - host: "mynginx.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mynginx
            port:
              number: 80
